import maya.cmds as cmds

def joint_scale_is_writable(joint):
    """
    Returns True only if scale XYZ can safely receive constraint connections.
    """

    attrs = [
        "scaleX",
        "scaleY",
        "scaleZ"
    ]

    for attr in attrs:

        plug = joint + "." + attr

        if not cmds.objExists(plug):
            return False

        try:
            locked = cmds.getAttr(
                plug,
                lock=True
            )

            settable = cmds.getAttr(
                plug,
                settable=True
            )

            incoming = cmds.listConnections(
                plug,
                source=True,
                destination=False,
                plugs=True
            ) or []

            if locked:
                return False

            if not settable:
                return False

            if incoming:
                return False

        except Exception:
            return False

    return True

def unlock_joint_driver_attrs(joint):
    """
    Unlocks the transform attrs that constraints need to drive.
    """

    attrs = [
        "translateX", "translateY", "translateZ",
        "rotateX", "rotateY", "rotateZ",
        "scaleX", "scaleY", "scaleZ"
    ]

    for attr in attrs:

        plug = joint + "." + attr

        if not cmds.objExists(plug):
            continue

        try:
            cmds.setAttr(plug, lock=False)
            cmds.setAttr(plug, keyable=True)
        except Exception:
            pass


def remove_joint_animation(joint, start=None, end=None):
    """
    Removes existing animation keys from a joint.
    This is done after the animation has already been baked to controls.
    """

    attrs = [
        "translateX", "translateY", "translateZ",
        "rotateX", "rotateY", "rotateZ",
        "scaleX", "scaleY", "scaleZ"
    ]

    kwargs = {
        "attribute": attrs,
        "option": "keys"
    }

    if start is not None and end is not None:
        kwargs["time"] = (start, end)

    try:
        cmds.cutKey(
            joint,
            **kwargs
        )
    except Exception:
        pass


def delete_existing_driver_constraints(joint):
    """
    Deletes constraints previously generated by this tool.
    """

    short = joint.split("|")[-1]

    possible = [
        short + "_ctrl_to_joint_parentConstraint",
        short + "_ctrl_to_joint_scaleConstraint"
    ]

    for node in possible:
        if cmds.objExists(node):
            cmds.delete(node)


# MAIN CONNECTION FUNCTION

def connect_fk_controls_to_joints(
    char,
    rig,
    start=None,
    end=None,
    remove_existing_joint_keys=True,
    create_scale_constraints=True,
    maintain_offset=False
):
    """
    Makes baked FK controls drive the original deform skeleton.

    Source:
        baked FK controls

    Target:
        original legacy joints

    This should be run AFTER:
        bake_joints_to_fk_controls()
    """

    if start is None:
        start = char.get(
            "startFrame",
            cmds.playbackOptions(q=True, min=True)
        )

    if end is None:
        end = char.get(
            "endFrame",
            cmds.playbackOptions(q=True, max=True)
        )

    start = int(start)
    end = int(end)

    print("=" * 80)
    print("CONNECTING FK CONTROLS TO JOINTS")
    print("Frame range: {} -> {}".format(start, end))
    print("=" * 80)

    constraints = []

    for slot, data in rig.items():

        # Skip metadata such as _FK_constraints
        if slot.startswith("_"):
            continue

        if not isinstance(data, dict):
            continue

        joint = data.get("joint")
        ctrl = data.get("ctrl")

        if not joint or not ctrl:
            cmds.warning("Skipping {}: missing joint or ctrl.".format(slot))
            continue

        if not cmds.objExists(joint):
            cmds.warning("Skipping {}: joint does not exist: {}".format(slot, joint))
            continue

        if not cmds.objExists(ctrl):
            cmds.warning("Skipping {}: ctrl does not exist: {}".format(slot, ctrl))
            continue

        unlock_joint_driver_attrs(joint)

        delete_existing_driver_constraints(joint)

        if remove_existing_joint_keys:
            remove_joint_animation(
                joint,
                start,
                end
            )

        short_joint = joint.split("|")[-1]

        pc_name = short_joint + "_ctrl_to_joint_parentConstraint"

        pc = cmds.parentConstraint(
            ctrl,
            joint,
            mo=maintain_offset,
            n=pc_name
        )[0]

        constraints.append(pc)

        if create_scale_constraints:

            if joint_scale_is_writable(joint):

                sc_name = short_joint + "_ctrl_to_joint_scaleConstraint"

                sc = cmds.scaleConstraint(
                    ctrl,
                    joint,
                    mo=maintain_offset,
                    n=sc_name
                )[0]

                constraints.append(sc)

            else:

                cmds.warning(
                    "Skipping scaleConstraint for {} because scale attrs are not writable.".format(
                        joint
                    )
                )

        print("Connected ctrl -> joint: {} -> {}".format(ctrl, joint))

    print("=" * 80)
    print("CONTROL TO JOINT CONNECTION COMPLETE")
    print("Created {} constraints.".format(len(constraints)))
    print("=" * 80)

    return constraints